[package]
name = "cortex-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Cortex 命令行客户端"

[[bin]]
name = "cortex"
path = "src/main.rs"

[dependencies]
cortex-core.workspace = true

tokio.workspace = true
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
